Registro/Registro/Controllers/ManagerController.cs
using Registro.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Registro.Controllers
{
    public class ManagerController : Controller
    {
        // GET: Manager

         
        public ActionResult Index(DataUser dataUser) 
        {
            if(Session["id_user"] == null)
            {
                Session["id_user"] = dataUser.id;
                Session["name_user"] = dataUser.Name;
                Session["last_name"] = dataUser.Last_name;
                Session["type_user"] = dataUser.Type;

            }

            
            if ((String)Session["type_user"] == "Manager")
            {
                Debug.WriteLine("Valido");
                ViewBag.name = Session["name_user"];
                ViewBag.lastName = Session["last_name"];

                Debug.WriteLine("paso por aca");
                return View(dataUser);
            }
            else
            {
                FinishSession(); 
                Debug.WriteLine("No valido");
                return RedirectToAction("Index", "Login");
            }

        }

        public ActionResult FinishSession()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Login"); 
        }

       


    }
}

Registro/Registro/Controllers/ProfessorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using Registro.Models;

namespace Registro.Controllers
{
    public class ProfessorsController : Controller
    {
        private RegistryEntities db = new RegistryEntities();

        // GET: Professors
        public ActionResult Index()
        {
          
            if (checkUser())
            {
                Debug.WriteLine("Valido");
                return View(db.Professors.ToList());
            }
            else
            {
                Debug.WriteLine("No valido");
                return RedirectToAction("FinishSession", "Manager");
            }
        }

        // GET: Professors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Professor professor = db.Professors.Find(id);
            if (professor == null)
            {
                return HttpNotFound();
            }
            return View(professor);
        }

        // GET: Professors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Professors/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,last_name,dni,activity")] Professor professor)
        {
            if (ModelState.IsValid)
            {
                db.Professors.Add(professor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(professor);
        }

        // GET: Professors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Professor professor = db.Professors.Find(id);
            if (professor == null)
            {
                return HttpNotFound();
            }
            return View(professor);
        }

        // POST: Professors/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,last_name,dni,activity")] Professor professor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(professor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(professor);
        }

        // GET: Professors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Professor professor = db.Professors.Find(id);
            if (professor == null)
            {
                return HttpNotFound();
            }
            return View(professor);
        }

        // POST: Professors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Professor professor = db.Professors.Find(id);


            var subjetsAsignedProfessor = from mat in db.Subjets
                                          where mat.id_profesor == id
                                          select mat;



          if(subjetsAsignedProfessor.Count() == 0)
          {
            //Borrado
            db.SaveChanges();
            db.Professors.Remove(professor); 
            db.SaveChanges();
            return RedirectToAction("Index"); 
            }
            else
            {
                ViewBag.Error = "It is not possible to unsubscribe a professor with assigned classes. Delete the assigned classes or assign it to a new professor";
                return View(professor);
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool checkUser()
        {
            bool valid = false;
            if((String)Session["type_user"] == "Manager")
            {
                valid = true;
            }
            return valid;
        }
    }
}

Registro/Registro/Controllers/SubjetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using Registro.Models;

namespace Registro.Controllers
{
    public class SubjetsController : Controller
    {
        private RegistryEntities db = new RegistryEntities();

        // GET: Subjets
        public ActionResult Index()
        {
            if (checkUser())
            {
                var subjets = db.Subjets.Include(s => s.Professor).Include(s => s.Day);
                return View(subjets.OrderBy(x => x.name).ToList());
            }
            else
            {
                Debug.WriteLine("No valido");
                return RedirectToAction("FinishSession", "Manager"); 
            }
        }

        // GET: Subjets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subjet subjet = db.Subjets.Find(id);
            if (subjet == null)
            {
                return HttpNotFound();
            }
            return View(subjet);
        }

        // GET: Subjets/Create
        public ActionResult Create()
        {

            var result = from profes in db.Professors
                         where profes.activity == true
                         select profes;

            ViewBag.id_profesor = new SelectList(result.ToList(), "id", "name");
            ViewBag.id_day = new SelectList(db.Days, "id", "day_name");
            return View();
        }

        // POST: Subjets/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,description,start_time,end_time,id_profesor,vacancies,id_day")] Subjet subjet)
        {
            if (ModelState.IsValid)
            {
                db.Subjets.Add(subjet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_profesor = new SelectList(db.Professors, "id", "name", subjet.id_profesor);
            ViewBag.id_day = new SelectList(db.Days, "id", "day_name", subjet.id_day);
            return View(subjet);
        }

        // GET: Subjets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subjet subjet = db.Subjets.Find(id);
            if (subjet == null)
            {
                return HttpNotFound();
            }

            
            //Busco solo los profesores activos.
            var result = from profes in db.Professors
                         where profes.activity == true
                         select profes;
            
            //Paso la lista al DrowDownList.
            ViewBag.id_profesor = new SelectList(result.ToList(), "id", "name", subjet.id_profesor);

            ViewBag.id_day = new SelectList(db.Days, "id", "day_name", subjet.id_day);
            return View(subjet);
        }

        // POST: Subjets/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,description,start_time,end_time,id_profesor,vacancies,id_day")] Subjet subjet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subjet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_profesor = new SelectList(db.Professors, "id", "name", subjet.id_profesor);
            ViewBag.id_day = new SelectList(db.Days, "id", "day_name", subjet.id_day);
            return View(subjet);
        }

        // GET: Subjets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subjet subjet = db.Subjets.Find(id);
            if (subjet == null)
            {
                return HttpNotFound();
            }
            return View(subjet);
        }

        // POST: Subjets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subjet subjet = db.Subjets.Find(id);

            //Busco las incripciones a la materia.
            var incripciones = from incr in db.Student_subjet
                               where incr.id_subjet == subjet.id
                               select incr;
         
            //elimino las incripciones.
            db.Student_subjet.RemoveRange(incripciones);
            //elimino la materia.
            db.Subjets.Remove(subjet); 
            
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool checkUser()
        {
            bool valid = false;
            if ((String)Session["type_user"] == "Manager")
            {
                valid = true;
            }
            return valid;
        }
    }
}

Registro/Registro/Views/Manager/EditProfessor.cshtml
@{
    ViewBag.Title = "EditProfessor";
    Layout = null;
    
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/StyleLogin.css" />
    <title>Login</title>
</head>

<body>
    <header>
        <div class="container">
            <h1>Login</h1>
        </div>
    </header>

    <div class="container">

       
        
           <div>
               <input type="submit" value="Serch" class="btn btn-default"
                      onclick="location.href='@Url.Action("SerchProfessor", "Manager")'" />
           </div>

        
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>


</html>

Registro/Registro/Views/Manager/FormProfessor.cshtml
@model Registro.Models.Professor

@{
    Layout = null;
    ViewBag.Title = "FormProfessor";
}
<meta name="viewport" content="width=device-width" />
<link rel="stylesheet" href="~/Content/StyleFormProfessor.css" />

<h2>FormProfessor</h2>

@using (Html.BeginForm("AddProfessor", "Manager", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Professor</h4>
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.last_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.last_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.last_name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dni, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dni, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dni)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.activity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.activity)
                    @Html.ValidationMessageFor(model => model.activity, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn-primary" /> 

            </div>
        </div>
    </div>

    <div class="msn-operation">
        @ViewBag.error
    </div>
}

<div>
    @Html.ActionLink("Back to manager page", "Index")
</div>

Registro/Registro/Views/Manager/Index.cshtml
@{
    ViewBag.Title = "Manager";
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/StyleManager.css" />

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
   

    <title>Manager</title>
</head>
     
<body>
    <header>
        <div class="container-fluid">
            <h1>
                Manager
                @ViewBag.name
                @ViewBag.lastName
            </h1>
        </div>
    </header>   
            <div class="navegation navbar-brand container">  
                <ul class="nav navbar-nav">
                    <li>
                        <div>@Html.ActionLink("Professor adminitration", "Index", "Professors", null, new { @class = "dropdown-option" })</div>
                    </li>
                    <li>    
                         <div>@Html.ActionLink("Subjet administration", "Index", "Subjets", null, new { @class = "dropdown-option" })</div>           
                    </li>
                    <li>
                        <div class="btn-logout">@Html.ActionLink("Logout","FinishSession","Manager",null, new { @class = "dropdown-option " })</div>
                    </li>
                </ul>
            </div>
</body>
        
</html>

Registro/Registro/Views/Manager/ListProfessor.cshtml
@model IEnumerable<Registro.Models.Professor>

@{
    ViewBag.Title = "ListProfessor";
    Layout = null;
}
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Content/StyleManager.css" />
    <title>List Profesor Editing</title>
</head>

<body>
    <header>
        <div class=" container">
            <h1>Edit Menu</h1>
        </div>
    </header>
    <br />
    <div class="container">
        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.last_name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.dni)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.activity)
                </th>
                <th>
                    <label>Edit item</label>
                </th>
            </tr>
     
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.last_name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.dni)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.activity)
                    </td>

                    <td>                               
                        @Html.ActionLink("Buscar", "ListProfessor", "Manager", item.id, new { @class= "btn-primary" })   
                    </td>
                </tr>
            }

        </table>
        <div class=" container">
            <div class=" form-group">
                <label>Name</label>
                <input type="text" value="tralala" />
            </div>
            <div class=" form-group">
                <label>Last Name</label>
                <input type="text" />
            </div>
            <div class=" form-group">
                <label>DNI</label>
                <input type="text"/>
            </div>
            <div class=" form-group">
                <label>Is Active</label>
                <input type="checkbox"/>
            </div>
            <div>
                <input type="submit" value="Update" class="btn-primary" />
            </div>
        </div>
    </div>
</body>